trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install -g gatsby-cli
  displayName: 'Install gatsby-cli'

- script: |
    yarn install
  displayName: 'Install dependencies'

- script: |
    yarn build
  displayName: 'Gatsby build'

- task: CopyFiles@2
  inputs:
    sourceFolder: 'public'
    contents: '**' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true 
  displayName: 'copy built site'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))


